version: "3.3"

services:
    bookweb-mongodb:
        container_name: bookweb-mongodb
        image: mongo:3-stretch
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27018:27018"
        command: mongod --port 27018
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpwd123
        networks:
            - bookweb_network

volumes:
    mongodb_data:

networks:
    bookweb_network:
        external: true
